---
parent: Api_v1_branches_update
name: ApiV1BranchesUpdatePutCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/branches/update
endpoint: /api/v1/branches/update
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "createdDate" : "{{@Var.createdDate}}",
      "inactive" : false,
      "createdBy" : "{{@Var.createdBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "branchName" : "{{@Var.branchName}}",
      "faxNumber" : "{{@Var.faxNumber}}",
      "atmAtBranch" : "{{@Var.atmAtBranch}}",
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "branchType" : "{{@Var.branchType}}",
      "id" : "{{@Var.id}}",
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin != @NULL'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
